version: '3.8'  # Specify Docker Compose version (adjust if needed)

services:
  prefect-postgres:
    image: postgres:latest
    container_name: prefect-postgres
    restart: always  # Ensure the container restarts automatically
    volumes:
      - prefectdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourTopS3cretPassw0rd!
      - POSTGRES_DB=prefect
  
volumes:
  prefectdb:  # Define the named volume for persistent data